Repository JNU-econovation/2021-2-I-AM-GROUND, pull requests merged in 2021-10, with the labels that each got.

#6 경주원(j8won) 자기소개
  profile/j8won.md
Labels: 자기소개, INTP

#15 김현지(kinhyeonji) 자기소개
  profile/kinhyeonji.md
Labels: 자기소개, ENFJ

#26 김서하(jnuseoha) 자기소개
  profile/jnuseoha.md
Labels: 자기소개, INFP

#14 김시형(Si-hyeong) 자기소개
  profile/Si-hyeong.md
Labels: 자기소개, ENFJ
