Repository JNU-econovation/2021-2-I-AM-GROUND, pull requests merged in 2021-12, with the labels that each got.

#2 주동혁(JUDONGHYEOK) 자기소개
  profile/JUDONGHYEOK.md
Labels: 자기소개, ISFP

#4 김민주(MINJOO-KIM) 자기소개
  profile/MINJOO-KIM.md
Labels: 자기소개, ISFJ

#17 최명선(myungsun7782) 자기소개
  profile/myungsun7782.md
Labels: 자기소개, ESFJ

#20 김정인(mywnajsldkf) 자기소개
  profile/mywnajsldkf.md
Labels: 자기소개, INTP, INFP

#23 박수현(sujasmine) 자기소개
  profile/sujasmine.md
Labels: 자기소개, ENFP

#24 정회형 (hotheadfactory) 자기소개
  profile/hotheadfactory.md
Labels: 자기소개, INTP

#25 김현지(kinhyeonji) 자기소개
  profile/kinhyeonji.md
Labels: 자기소개, ENFJ
